language: node_js
node_js:
  - 10
branches:
  only:
    - master
    - develop
    - /^release-.*$/
cache:
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.0
  - export PATH="$HOME/.yarn/bin:$PATH"
env:
  - NODE_ENV=test
install:
  - yarn install
script:
  - yarn test
  - echo $PASSWORD_SSH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG

before_deploy:
  - apt-get install sshpass

deploy:
  - provider: script
    skip_cleanup: true
    script: echo hiiii!
    on:
      branch: master


