language: node_js
services:
  - docker
node_js:
  - node
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn lint
  - yarn test:coveralls
  - yarn install
  - yarn build
  - docker build -t psalguero/nestjs-task-management:latest .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    all_branches: true

notifications:
  email: false