language: node_js
node_js:
  - node
branches:
  only:
    - master
    - develop
    - /^release-.*$/
cache:
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.0
  - export PATH="$HOME/.yarn/bin:$PATH"
env:
  - NODE_ENV=test
install:
  - yarn install
script:
  - yarn lint
  - yarn test:coveralls
notifications:
  email: false